services:
  - type: web
    name: on-page-seo-advisor-1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5 --log-level info src.main:app
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project
      - key: PYTHON_VERSION
        value: 3.11.7 